version: "3.9"

services:
  db:
    build: ./db
    container_name: lr-db
    environment:
      POSTGRES_DB: lr_db
      POSTGRES_USER: lr_user
      POSTGRES_PASSWORD: lr_password
    ports:
      - "15432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lr_user -d lr_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: lr-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_PUBLIC_BASE_URL: "http://localhost:8080"
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/lr_db
      SPRING_DATASOURCE_USERNAME: lr_user
      SPRING_DATASOURCE_PASSWORD: lr_password
      SECURITY_JWT_SECRET: "REm6m3s8B7gqf7Gk9gqJ5O1p4HjK0J8JkGVmQ0GJ5a0="   # <-- EXEMPLE Base64 32+ bytes
      SECURITY_JWT_EXPIRATION_MINUTES: "60"                                  # <-- optionnel
    volumes:
      - ./uploads:/data/uploads
    ports:
      - "8080:8080"


  frontend:
    build: ./frontend
    container_name: lr-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
