INSERT INTO "user" (
    id,
    email,
    password,
    provider,
    provider_id,
    roles,
    firstname,
    lastname,
    phone,
    profil_photo,
    status,
    sector,
    created_at,
    updated_at
) VALUES
    (
        gen_random_uuid(),
        'admin@gmail.com',
        '$2a$12$Z7mLc0S231WHVaJNouXqpOfX56Ch3GorxnKtM4aT4GjvX7QkWg3Zm',
        'LOCAL',
        NULL,
        'ADMIN',
        'Admin',
        'Admin',
        '0000000000',
        NULL,
        'ACTIVE',
        'IT',
        CURRENT_TIMESTAMP,
        NULL
    );