ALTER TABLE "user"
    ADD COLUMN IF NOT EXISTS firstname VARCHAR(255),
    ADD COLUMN IF NOT EXISTS lastname VARCHAR(255),
    ADD COLUMN IF NOT EXISTS phone VARCHAR(50),
    ADD COLUMN IF NOT EXISTS profil_photo VARCHAR(512),
    ADD COLUMN IF NOT EXISTS status VARCHAR(50) NOT NULL DEFAULT 'ACTIF',
    ADD COLUMN IF NOT EXISTS sector VARCHAR(255);
