CREATE TABLE subscription_billing
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    plan_name      VARCHAR(100)                            NOT NULL,
    price_ht       DOUBLE PRECISION                        NOT NULL,
    billing_period VARCHAR(20)                             NOT NULL,
    CONSTRAINT pk_subscription_billing PRIMARY KEY (id)
);